name: GALANTE NEXUS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        uses: espressif/esp-idf-ci-action@v1
        with:
          path: galante_nexus_source.zip
          target: esp32s3
          command: build
